### ISSUE TITLE
magnetic fields do no work

### ISSUE THREAD

**Issue by andrewdurkiewicz** [ASU-CompMethodsPhysics-PHY494/final-stern-gerlach-simulation#3]
@ion201 @gvetaw Hey, if magnetic fields do no work, how are our particles accelerating in the x and z direction? What is doing the work?

**Comment by ion201** [comment]
@ASU-CompMethodsPhysics-PHY494/stern-gerlach-simulation 

The code assumes that the y-velocity is constant. I don't think that is the case but it isn't obvious since that wouldn't substantially impact the shape of the outcome (assuming a relatively large v0). In that case, the y velocity should scale such that the velocity magnitude is constant.
